openapi: "3.1.0"
info:
  title: Cooler Loans
  version: "1.1"
servers:
  - url: https://olympusdao-cooler-loans-api-prod.web.app/
    description: Production
  - url: https://olympusdao-cooler-loans-api-dev.web.app/
    description: Development
paths:
  /:
    get:
      summary: Retrieves all Cooler Loans snapshots between the given dates.
      operationId: getSnapshots
      tags:
        - snapshot
      parameters:
        - name: startDate
          in: query
          description: The start date (YYYY-MM-DD) of the loan period
          required: true
          schema:
            type: string
        - name: beforeDate
          in: query
          description: The date (YYYY-MM-DD) up to (but not including) which records should be retrieved
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    type: array
                    items:
                      $ref: "snapshot.yaml"
